development:
  sessions:
    default:
      uri: "mongodb://aditya:aditya0007@kahana.mongohq.com:10087/mongoDB"
      options:
       # skip_version_check: true
       # safe: true
test:
  sessions:
    default:
      database: mongoblog_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      #edit uri with your user name and password
      uri: "mongodb://aditya:aditya0007@kahana.mongohq.com:10087/mongoDB"
      options:
       # skip_version_check: true
       # safe: true
