development:
  server: "http://purple-fireball-40-162943.apse1.nitrousbox.com:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://mychatapp.herokuapp.com/faye"
  secret_token: "da43b57b52e0e4abbaf4347f41034803c19e08ccfc0a05b1cdeafa6e6ceb3caa"
  signature_expiration: 3600 # one hour
